### ISSUE TITLE
2021 Spring-Summer Semester Plan

### ISSUE THREAD

**Issue by Locietta** [Locietta/blogs#13]
## 2021春夏学期的计划表

大二了，该<del>搞点事情</del>好好学习了

> 新的一年了
> 拖计划也是常态了（尬笑

--------------------------------

#### 实现一个真正意义上程序软件
> Learning List
- Modern C++ (主要是OOP和template方面的)
- Modern Qt (主要是Qt quick)
- C# UWP

#### 写一些算法相关的博客：
- [x] 走迷宫DFS&BFS
- [ ] 剪枝/A*&IDA*
 
#### 知乎上写一点数学：
- 数值分析相关（咕
- 实变
- 备战数竞国赛

#### 其他比较困难的东西：
- [ ] 编译原理（初步目标是重构命令行计算器）
- [ ] 翻译LLVM自创语言编译器前端教程（在做了，在做了）
- [ ] LLVM（实现一个LLVM编译器前端）
- [x] 写一个C/C++小游戏
- [ ] 函数式（Haskell）

-----------------------------

### Legacy of Last Year's Plan(#5)

> 暑假条目中已完成/未完成，但现在热情不高的部分

- [ ] 机器证明（Coq(?) -> Lean）
- [x] 类型论/Lambda演算
- [x] 学习C++11/17/20
- [ ] 学习网络爬虫（Python/C++）
- [ ] 训练机器学习模型
- [x] 学习JS/TS
- [ ] 学习vsc插件开发（<del>这好像是寒假的计划来着（（</del>
- [ ] 学习编曲（？）
- [x] 扒谱
- [x] 像素风绘画（？）

------------------------------

**Comment by Locietta** [comment]
等我考试结束了在开始（

**Comment by ZJU-JerryMiao** [comment]
`shutdown -s`

**Comment by Locietta** [comment]
在做了在做了（

**Comment by Locietta** [comment]
秋学期结束了））

**Comment by ZJU-JerryMiao** [comment]
【自动回复】邮件已成功投递，将会及时查收。祝好，Miao StudioJerry
