### ISSUE TITLE
How to compile the lateset gcc on WSL

### ISSUE THREAD

**Issue by Locietta** [Locietta/blogs#3]
# 在WSL上编译安装gcc10

在WSL上编译安装最新版本的编译器，之后的C开发环境应该会以WSL为主啦

（当然，这个博客也适用于各个Linux发行版）

-----------------------------

## GCC10.2.0

GCC10.2于2020/07/23发布，修复了10.1存在的一系列bug并且增强了一些支持

### 1 下载源代码

[GNU镜像列表](https://www.gnu.org/prep/ftp.html)

我选择了从[gcc阿里云镜像](https://mirrors.aliyun.com/gnu/gcc/)下载gcc10.2.0源代码

下载完成后得到一个压缩包👇

![image](https://user-images.githubusercontent.com/53137814/88502277-86e5b580-d000-11ea-9beb-69f04b98bde7.png)

### 2 解压压缩包

将它放到WSL目录下

> 请务必打开WSL使用cp或者mv命令进行操作，直接利用windows资源管理器移动文件可能会造成不能识别的错误

```bash
# 打开bash
cp /mnt/.../gcc-10.2.0.tar.gz ~/gcc
```

``cd``到压缩包目录下输入``tar zxvf gcc-10.2.0.tar.gz``进行解压

> 解压大约耗时10分钟

### 3 配置

gcc自带configure脚本帮助你配置好一切环境并生成makefile，可以用``--prefix=``来指定编译目录，否则就将直接编译到当前目录

configure必须在解压出来的gcc目录下才能访问

> 注意GCC不支持直接编译到源代码文件夹，所以需要我们另外在解压得到的文件夹中建一个build文件夹

```
mkdir build
cd build
../configure # 利用GCC自带的脚本进行配置
```

然后如果之前没有编译过的话，会提示你缺了一些依赖👇

![QQ截图20200726203647](https://user-images.githubusercontent.com/53137814/88689424-0cff1a80-d12d-11ea-820d-f1d5bf9049ff.png)

...然后网上的一些教程就会告诉你：去那些包的官网下源码然后**自己编译**接着折腾``LD_LIBRARY_PATH``变量

> 说的就是你C S D N

> 不过这样的教程还挺多的（博客园和阿里云社区上也都有

只能说，不要信这些鬼话(血与泪的教训)

## 不要自己下载编译安装这些依赖！！！

> ![image](https://user-images.githubusercontent.com/53137814/88503234-a8946c00-d003-11ea-9961-77cf6e0be26e.png)
> Stackoverflow上这位仁兄说的太好了
> 就是说嘛，都0202年了，GCC怎么可能还强制要求你自己去折腾呢？🤦‍
> 况且自己折腾完全没法处理各种环境配置问题。。

gcc在./contrib目录下提供了download_prerequisite脚本用于下载并解压需要的包

所以只需执行``./contrib/download_prerequisite``即可，下载没有进度条，需要一定的时间

一段时间的等待过后，当前目录下就解压好所有所需的依赖了，接下来重新进入``build``文件夹配置

```
cd build
../configure # --prefix=xxx
```

再次等待一小会后，配置成功！

### 4 编译&安装

回到源代码文件夹执行``make -j 32`` (其中``-j``用于指定线程数)

编译相当耗时，如果有没安装的依赖，它会自动配置编译并安装，最后才是编译gcc本体

编译完成大约需要2-4个小时**可以先睡一觉**

最后``sudo make install``完成安装

查看gcc/g++版本↓

![image](https://user-images.githubusercontent.com/53137814/88689529-27d18f00-d12d-11ea-9047-b8bf05afccb8.png)

现在可以体验gcc10带来的concepts, ranges, coroutine等C++20特性了😀

--------------------------------

## <del>下面是只写了个开头的Clang10.0.1编译</del>

> ## Clang10.0.1
> 
> [官方编译文档](https://llvm.org/docs/CMake.html#quick-start)
> 
> Clang的build基于`cmake`，这也意味着可以在windows上采用完全相同的方式来编译Clang
> 
> 不过要编译Clang10的话，cmake的版本至少要在3.13.4以上
> 
> > 官网文档的第一行说明👇
> > ![image](https://user-images.githubusercontent.com/53137814/89099303-d40ec080-d420-11ea-8066-d44bf8f98375.png)
> 
> 但是...
> 
> ![image](https://user-images.githubusercontent.com/53137814/89099327-fc96ba80-d420-11ea-97de-06657dff426b.png)
> 
> ubuntu1804目前apt里最新版的cmake也只有3.10.x，所以要想build最新的clang就只能自己去cmake官网下载cmake源码来编译了

**Comment by Locietta** [comment]
## gcc下载速度感人
而且还老断（豹毙
换阿里源一下就下好了

[gcc阿里源](https://mirrors.aliyun.com/gnu/gcc/)

**Comment by Locietta** [comment]
> ## gcc下载速度感人
> 而且还老断（豹毙
> 换阿里源一下就下好了

下载的是两天前刚更新的10.2

**Comment by Locietta** [comment]
#4 各种压缩包的解压参考

**Comment by Locietta** [comment]
## gcc安装大失败

请先阅读安装文档[https://gcc.gnu.org/install/index.html](https://gcc.gnu.org/install/index.html)😭

还有：
## 小 心 C S D N
--------------
我早该google的，白费我3hours' painful trial in vain

**Comment by Locietta** [comment]
![image](https://user-images.githubusercontent.com/53137814/88494844-598e0d00-cfea-11ea-8256-2d6511f513b6.png)
成啦~

**Comment by Locietta** [comment]
好像ubuntu18.04有一个ppa在跟进gcc10

```bash
sudo add-apt-repository ppa:ubuntu-toolchain-r/test  # 添加ppa
sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test # 删除ppa
```

添加了ppa之后，只要``sudo apt update``一下，就可以看到gcc10的更新了

------------------------------

不过只有gcc10.1，想要最新版还是得自己动手

**Comment by Locietta** [comment]
> #4 各种压缩包的解压参考

现在看起来根本不需要，全怪CSDN（

不过学了也挺好😇

**Comment by Locietta** [comment]
![image](https://user-images.githubusercontent.com/53137814/89103064-a5eda880-d441-11ea-9570-ba8cc6d6d937.png)

--------------------

gcc10.2编译出来之后似乎`libstdc++.so.6`的版本有点不太对劲

```
libstdc++.so.6 version glibcxx_3.4.26' not found
```

**Comment by Locietta** [comment]
> ![image](https://user-images.githubusercontent.com/53137814/89103064-a5eda880-d441-11ea-9570-ba8cc6d6d937.png)
> 
> gcc10.2编译出来之后似乎`libstdc++.so.6`的版本有点不太对劲
> 
> ```
> libstdc++.so.6 version glibcxx_3.4.26' not found
> ```

啊这，我还一不小心给删库了

我是不是该跑路了（（（

**Comment by Locietta** [comment]
一波折腾，用了上面的ppa装了下ubuntu的gcc10.1

然后就把`libstdc++.so.6`给修好啦

**Comment by Locietta** [comment]
发现好像clang在各个平台都有比较新的binary release

（所以...

-----------------------------

> 咕咕咕🕊

**Comment by morninghut** [comment]
> # 在WSL上编译安装gcc10
> 在WSL上编译安装最新版本的编译器，之后的C开发环境应该会以WSL为主啦
> 
> （当然，这个博客也适用于各个Linux发行版）
> 
> ## GCC10.2.0
> GCC10.2于2020/07/23发布，修复了10.1存在的一系列bug并且增强了一些支持
> 
> ### 1 下载源代码
> [GNU镜像列表](https://www.gnu.org/prep/ftp.html)
> 
> 我选择了从[gcc阿里云镜像](https://mirrors.aliyun.com/gnu/gcc/)下载gcc10.2.0源代码
> 
> 下载完成后得到一个压缩包👇
> 
> ![image](https://user-images.githubusercontent.com/53137814/88502277-86e5b580-d000-11ea-9beb-69f04b98bde7.png)
> 
> ### 2 解压压缩包
> 将它放到WSL目录下
> 
> > 请务必打开WSL使用cp或者mv命令进行操作，直接利用windows资源管理器移动文件可能会造成不能识别的错误
> 
> ```shell
> # 打开bash
> cp /mnt/.../gcc-10.2.0.tar.gz ~/gcc
> ```
> 
> `cd`到压缩包目录下输入`tar zxvf gcc-10.2.0.tar.gz`进行解压
> 
> > 解压大约耗时10分钟
> 
> ### 3 配置
> gcc自带configure脚本帮助你配置好一切环境并生成makefile，可以用`--prefix=`来指定编译目录，否则就将直接编译到当前目录
> 
> configure必须在解压出来的gcc目录下才能访问
> 
> > 注意GCC不支持直接编译到源代码文件夹，所以需要我们另外在解压得到的文件夹中建一个build文件夹
> 
> ```
> mkdir build
> cd build
> ../configure # 利用GCC自带的脚本进行配置
> ```
> 
> 然后如果之前没有编译过的话，会提示你缺了一些依赖👇
> 
> ![QQ截图20200726203647](https://user-images.githubusercontent.com/53137814/88689424-0cff1a80-d12d-11ea-820d-f1d5bf9049ff.png)
> 
> ...然后网上的一些教程就会告诉你：去那些包的官网下源码然后**自己编译**接着折腾`LD_LIBRARY_PATH`变量
> 
> > 说的就是你C S D N
> 
> > 不过这样的教程还挺多的（博客园和阿里云社区上也都有
> 
> 只能说，不要信这些鬼话(血与泪的教训)
> 
> ## 不要自己下载编译安装这些依赖！！！
> > ![image](https://user-images.githubusercontent.com/53137814/88503234-a8946c00-d003-11ea-9961-77cf6e0be26e.png)
> > Stackoverflow上这位仁兄说的太好了
> > 就是说嘛，都0202年了，GCC怎么可能还强制要求你自己去折腾呢？🤦‍
> > 况且自己折腾完全没法处理各种环境配置问题。。
> 
> gcc在./contrib目录下提供了download_prerequisite脚本用于下载并解压需要的包
> 
> 所以只需执行`./contrib/download_prerequisite`即可，下载没有进度条，需要一定的时间
> 
> 一段时间的等待过后，当前目录下就解压好所有所需的依赖了，接下来重新进入`build`文件夹配置
> 
> ```
> cd build
> ../configure # --prefix=xxx
> ```
> 
> 再次等待一小会后，配置成功！
> 
> ### 4 编译&安装
> 回到源代码文件夹执行`make -j 32` (其中`-j`用于指定线程数)
> 
> 编译相当耗时，如果有没安装的依赖，它会自动配置编译并安装，最后才是编译gcc本体
> 
> 编译完成大约需要2-4个小时**可以先睡一觉**
> 
> 最后`sudo make install`完成安装
> 
> 查看gcc/g++版本↓
> 
> ![image](https://user-images.githubusercontent.com/53137814/88689529-27d18f00-d12d-11ea-9047-b8bf05afccb8.png)
> 
> 现在可以体验gcc10带来的concepts, ranges, coroutine等C++20特性了😀
> 
> ## ~下面是只写了个开头的Clang10.0.1编译~
> > ## Clang10.0.1
> > [官方编译文档](https://llvm.org/docs/CMake.html#quick-start)
> > Clang的build基于`cmake`，这也意味着可以在windows上采用完全相同的方式来编译Clang
> > 不过要编译Clang10的话，cmake的版本至少要在3.13.4以上
> > > 官网文档的第一行说明👇
> > > ![image](https://user-images.githubusercontent.com/53137814/89099303-d40ec080-d420-11ea-8066-d44bf8f98375.png)
> > 
> > 
> > 但是...
> > ![image](https://user-images.githubusercontent.com/53137814/89099327-fc96ba80-d420-11ea-97de-06657dff426b.png)
> > ubuntu1804目前apt里最新版的cmake也只有3.10.x，所以要想build最新的clang就只能自己去cmake官网下载cmake源码来编译了

感谢教程！
为什么我自己折腾了好几天才看到 **不需要自己下载安装依赖** 😂
btw，考虑发布到知乎吗？We need the correct tutorial like this！👍

**Comment by Locietta** [comment]
我原来还写过这个[ ﾟ∀。]!

事实上获得最新的编译器最省事的办法是使用一个更新及时的滚动发行版（比如Arch之类的）

发到知乎的话，要翻新一遍，有点懒的整（如今已经是gcc12/llvm15了喂

另外现在回头看的话：这种类型的博客写得再怎么好，写完的那一天就过时了，最终也会变成误导人的东西。开源软件怎么编译最好的教程一定是它的官方文档，毕竟如果编译不了都没法让人contribute[ ﾟ∀。]
